version: '3.9'
services:
  django:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - ./projet:/var/lib/projet
    command: python /var/lib/projet/django/sentimentAnalysis/manage.py runserver 0.0.0.0:8000
    
    